spring.application.name=usuarioApi

#Credenciales
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update

# Credenciales de seguridad para el usuario en memoria (cargadas desde .env)
spring.security.user.name=${USER_NAME}
spring.security.user.password=${PASSWORD}

logging.level.org.hibernate.SQL=DEBUG
logging.level.org.springframework.web=DEBUG
