spring.application.name=ApiGateWay
server.port=8888

#Credenciales
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update

jwt.secret=clave_super_segura_de_mas_de_64_bytes_de_longitud_esto_es_necesario_para_HS512

# Endpoint de la API de Gestión de Usuarios
services.usuarios.base-url=http://localhost:8080
services.usuarios.base-path=/api/usuariosApi

#   Endpoint de la API de Gestión de Regiones
services.regiones.base-url=http://localhost:8080
services.regiones.base-path=/api/regionesApi

#   Endpoint de la API de Gestión de Comunas
services.comunas.base-url=http://localhost:8080
services.comunas.base-path=/api/comunasApi

#   Endpoint de la API de Gestión de SexoUsuario
services.sexousuario.base-url=http://localhost:8080
services.sexousuario.base-path=/api/sexosApi

#   Endpoint de la API de Gestión de Oficio
services.oficio.base-url=http://localhost:8080
services.oficio.base-path=/api/oficiosApi

#  Endpoint de la API de Gestión de Tipos de Usuario
services.tiposusuario.base-url=http://localhost:8080
services.tiposusuario.base-path=/api/tiposUsuarioApi

# Endpoint de la API de Publicaciones
services.publicaciones.base-url=http://localhost:8085
services.publicaciones.base-path=/api/publicacionesApi

# Endpoint de la API de resenias
services.resenias.base-url=http://localhost:8085
services.resenias.base-path=/api/reseniasApi

# Endpoint de la API de Perfiles
services.perfiles.base-url=http://localhost:8080
services.perfiles.base-path=/api/perfilesApi

# Endpoint de la API de Respuestas resenias
services.respuestas.resenias.base-url=http://localhost:8085
services.respuestas.resenias.base-path=/api/respuestasReseniasApi

# Endpoint de la API de Chat
services.chat.base-url=http://localhost:8080
services.chat.base-path=/api/chatApi


