spring.application.name=ApiGateWay
server.port=8888

#Credenciales
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update

jwt.secret=clave_super_segura_de_mas_de_64_bytes_de_longitud_esto_es_necesario_para_HS512

# Endpoint de la API de Gestión de Usuarios
services.usuarios.base-url=http://localhost:8080
services.usuarios.base-path=/api/usuariosApi
