name: Java CI with Maven & Security Scan

on:
  push:
    branches: [ "main", "develop", "desarrollo-apis" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout del código
      uses: actions/checkout@v4

    - name: Configurar JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Compilar y Empaquetar (sin tests)
      run: mvn -B package -DskipTests
      working-directory: Apis/usuarioApi

    - name: Análisis de Seguridad (Dependency Check - usuarioApi)
      # Paso que busca si las librerías (pom.xml) tienen fallos conocidos
      run: mvn org.owasp:dependency-check-maven:check
      working-directory: Apis/usuarioApi
      continue-on-error: true # Para que no bloquee todo si encuentra algo menor al inicio

  code-quality:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Super-Linter
      # Este es el "robot" que revisa que tu código esté limpio 
      uses: github/super-linter@v5
      env:
        VALIDATE_ALL_CODEBASE: false
        DEFAULT_BRANCH: main
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        VALIDATE_JAVA: true